name: test

on: pull_request

jobs:
    run_test:
        strategy:
            matrix:
                go-version: [1.17.x]
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        
        steps:
            -   name: Install Go
                uses: actions/setup-go@v2
                with:
                    go-version: ${{ matrix.go-version }}
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Run coverage
                run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
                env:
                    CI_ENV: "TRUE"
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v2
