name: test

on: pull_request

jobs:
    run_test:
        name: Invite Test
        runs-on: ubuntu-latest
        
        steps:
            -   name: Set up Go 1.17
                uses: actions/setup-go@v2
                with:
                    go-version: 1.17
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 2
            -   name: Run coverage
                run: go test -race -coverprofile="coverage.txt" -covermode=atomic
                env:
                    CI_ENV: "TRUE"
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v2
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: ./coverage.txt
